# Generated by Django 2.2.3 on 2019-07-20 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=55, verbose_name='Название уровня')),
            ],
            options={
                'verbose_name_plural': 'Уровни',
                'verbose_name': 'Уровень',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
            ],
            options={
                'verbose_name_plural': 'Типы оборудования',
                'verbose_name': 'Тип оборудования',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.CharField(max_length=25, verbose_name='Номер пропуска')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_from', models.DateTimeField(help_text='Срок годности (от)', verbose_name='От')),
                ('date_to', models.DateTimeField(help_text='Срок годности (до)', verbose_name='До')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не активен'), (1, 'Активный'), (2, 'Просрочен'), (3, 'Заблокирован')], default=1, verbose_name='Статус')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccessLevel', verbose_name='Уровень доступа')),
            ],
            options={
                'verbose_name_plural': 'Пропуски',
                'verbose_name': 'Пропуск',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
            ],
            options={
                'verbose_name_plural': 'Тип документов',
                'verbose_name': 'Тип документа',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=55, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=55, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не активен'), (1, 'Активный'), (2, 'Просрочен документ')], default=0, verbose_name='Статус')),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подрядчик')),
                ('permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Permit', verbose_name='Пропуск')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_type', models.PositiveIntegerField(choices=[(0, 'Новое'), (1, 'Выполнено')], default=0, verbose_name='Тип события')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Новое'), (1, 'Выполнено'), (2, 'Отклонёно')], default=0, verbose_name='Статус')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name_plural': 'События',
                'verbose_name': 'Событие',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('access', models.PositiveIntegerField(choices=[(0, 'Не проверено'), (1, 'Проверен'), (2, 'Отклонён')], default=0, verbose_name='Разрешение')),
                ('type_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EquipmentType', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name_plural': 'Оборудование',
                'verbose_name': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_from', models.DateTimeField(blank=True, help_text='Дата и время (от)', verbose_name='Срок действия')),
                ('date_to', models.DateTimeField(blank=True, help_text='Дата и время (до)', verbose_name='Срок действия')),
                ('file', models.FileField(help_text='Загрузите скан документа', upload_to='uploads/documents/', verbose_name='Файл')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Новый'), (1, 'Проверен'), (2, 'Отклонён')], default=0, verbose_name='Статус')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person', verbose_name='Сотрудник')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TypeDocument', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name_plural': 'Документы',
                'verbose_name': 'Документ',
            },
        ),
    ]
